### ISSUE TITLE
Create Python code needed to geocode flat SQL Tables into Featureclasses

### ISSUE THREAD

**Issue by dspinosa** [Innovate-Inc/CRS#10]
Create Python code needed to geocode flat SQL Tables into Feature classes.  Might need to find a way to catch exceptions and allow CRS team to review.  This will eventually be a scheduled task that fires after the data are loaded into SQL Server from Salesforce.

**Comment by jlherring** [comment]
-  Are we expecting additional tables from Salesforce outside the scope of this export or just more data w/in these tables?--- **Just these tables**
  (Can we create views w/in SQL manually based the different fields of each table, or do we need to allow for flexibility in the future??) --- creating manually in the SQL table
- When Salesforce data is exported in the future, will it be a total rewrite of the database, or just append additional records to tables? In which case the script needs to identify new records? --- **for now, plan on rewriting the database**
- What format should the exceptions be communicated in? (csv listing table/address that didn't match, html report, email?)
