### ISSUE TITLE
GIS Team to test Access to SQL Server And GIS Server

### ISSUE THREAD

**Issue by dspinosa** [Innovate-Inc/CRS#2]
Test access to SQL Server and ArcGIS Server box... VPN and Remote Desktop.

**Comment by dwoodinnovate** [comment]
David and Jenny both have emails sent to CRS team requesting access credentials. Currently provided credentials do not provide needed access.

**Comment by dwoodinnovate** [comment]
David and Jenny both have emails sent to CRS team requesting access credentials. Currently provided credentials do not provide needed access.

**Comment by dwoodinnovate** [comment]
David and Jenny both have emails sent to CRS team requesting access credentials. Currently provided credentials do not provide needed access.

**Comment by dwoodinnovate** [comment]
David and Jenny both have emails sent to CRS team requesting access credentials. Currently provided credentials do not provide needed access.

**Comment by dwoodinnovate** [comment]
David and Jenny both have emails sent to CRS team requesting access credentials. Currently provided credentials do not provide needed access.
