### ISSUE TITLE
Need access to Salesforce data

### ISSUE THREAD

**Issue by jlherring** [Innovate-Inc/CRS#20]
Need to get access to data and perform and post-processing necessary to put in map
- [x] Grassroots action takers – still need to identified?
- [x] States (Us Senate) – found, not exported
- [x] Names of Members of Congress – found, not exported
- [x] Congressional Committee/Subcommittee – found, but not exported
- [x] Diocese -Identified CBI vs PAC yet? PAC identified, not CBI
- [x] Farmer to Farmer volunteers – still waiting for CRS to provide

**Comment by dspinosa** [comment]
Mark now has all the data being extracted from Salesforce.
