### ISSUE TITLE
Schedule time to with CRS Team to deploy to their servers

### ISSUE THREAD

**Issue by dspinosa** [Innovate-Inc/CRS#26]
The CRS team would like to observe what has to be done rolling the GIS data from our server to theirs.  They requested we schedule a time with them when we are ready to deploy to their server.  This will assist them in resolving issues that may come up during deployment.

**Comment by jlherring** [comment]
Dev environment is setup, but have not yet gone to production

**Comment by jlherring** [comment]
CRS setup prod environments themselves
